import faker from 'faker';
export const hardCodedCelebs = [
  {
    name: 'Lionel Messi',
    image: '/celebs/lionel.jpeg',
    link: '',
    price: 0,
    profession: '',
  },
  {
    name: faker.name.findName(),
    image: '/celebs/.jpeg',
    link: '',
    price: 0,
    profession: '',
  },
  {
    name: 'Floyd Mayweather',
    image: '/celebs/floyd.jpeg',
    link: '',
    price: 0,
    profession: '',
  },

  {
    name: 'The Game',
    image: '/celebs/the-game.jpeg',
    link: '',
    price: 0,
    profession: '',
  },
  {
    name: 'Gwyneth Paltrow',
    image: '/celebs/gwen.jpeg',
    link: '',
    price: 0,
    profession: '',
  },
  {
    name: 'Roger Ver',
    image: '/celebs/ver.jpeg',
    link: '',
    price: 0,
    profession: '',
  },
  {
    name: 'Redfoo',
    image: '/celebs/redfoo.jpeg',
    link: '',
    price: 0,
    profession: '',
  },
  {
    name: faker.name.findName(),
    image: '/celebs/.jpeg',
    link: '',
    price: 0,
    profession: '',
  },

  {
    name: 'Martina Hingis',
    image: '/celebs/martina.jpeg',
    link: '',
    price: 0,
    profession: '',
  },
  {
    name: faker.name.findName(),
    image: '/celebs/.jpeg',
    link: '',
    price: 0,
    profession: '',
  },
  {
    name: faker.name.findName(),
    image: '/celebs/.jpeg',
    link: '',
    price: 0,
    profession: '',
  },
  {
    name: 'Jessica VerSteeg',
    image: '/celebs/jessica.jpeg',
    link: '',
    price: 0,
    profession: '',
  },
  {
    name: 'Ashton Kutcher',
    image: '/celebs/ashton.jpeg',
    link: '',
    price: 0,
    profession: '',
  },

  {
    name: faker.name.findName(),
    image: '/celebs/.jpeg',
    link: '',
    price: 0,
    profession: '',
  },
  {
    name: faker.name.findName(),
    image: '/celebs/.jpeg',
    link: '',
    price: 0,
    profession: '',
  },
  {
    name: faker.name.findName(),
    image: '/celebs/.jpeg',
    link: '',
    price: 0,
    profession: '',
  },
  {
    name: 'Mike Tyson',
    image: '/celebs/tyson.jpeg',
    link: '',
    price: 0,
    profession: '',
  },
  {
    name: 'Jamie Foxx',
    image: '/celebs/jamie.jpeg',
    link: '',
    price: 0,
    profession: '',
  },
  {
    name: faker.name.findName(),
    image: '/celebs/.jpeg',
    link: '',
    price: 0,
    profession: '',
  },
  {
    name: 'Mel B',
    image: '/celebs/mel.jpeg',
    link: '',
    price: 0,
    profession: '',
  },
];
